reference: resources/reference/GCA_026108075.1_ASM2610807v1_genomic.fna
samples: config/samples.tsv

wtdbg2_assemble:
  mem: 40000
  time: "6:00:00"
  threads: 20

wtdbg2_consensus:
  mem: 30000
  time: "1:30:00"
  threads: 20