reference: resources/reference/GCA_026108075.1_ASM2610807v1_genomic.fna
genes: resources/genes/GCA_026108075.1_ASM2610807v1_genomic.bed
samples: config/samples.tsv



minimap2:
  mem: 10000
  time: "2:00:00"
  threads: 20

samtools:
  mem: 10000
  time: "1:00:00"
  threads: 4

mosdepth:
  mem: 10000
  time: "1:00:00"
  threads: 4

alfred:
  mem: 10000
  time: "1:00:00"
  
bwa_index:
  mem: 20000
  time: "2:00:00"

bwa_mem:
  mem: 10000
  time: "5:00:00"
  threads: 20

wtdbg2_assemble:
  mem: 40000
  time: "6:00:00"
  threads: 20

wtdbg2_consensus:
  mem: 30000
  time: "1:30:00"
  threads: 20

quast:
  mem: 30000
  time: "10:00:00"
  threads: 20

canu:
  mem: 50000
  time: "36:00:00"
  threads: 32